### PR TITLE
Check for null values during search to avoid throwing javascript erro…

### PR DESCRIPTION
**Pull request by Blackbaud-ScottVossen**
…rs when an object has a property with an explicit null value

This is a small fix for issue #6 that I logged.

### CODE REVIEW

**Comment by travist** [comment]
Looks good. Thanks @Blackbaud-ScottVossen!

**Comment by travist** [comment]
released as v0.1.10 on npm. Thanks again!

**Comment by Blackbaud-ScottVossen** [comment]
Awesome! Any idea on when I might be able to see this version updated in the angular form renderer (ngFormio)?

**Comment by travist** [comment]
We are waiting on another bug to get fixed, which @zackurben is working on right now. Once he does, we will roll out a new version of the renderer with this in place. @zackurben do you have an ETA for the issue you are working on with the renderer?

**Comment by zackurben** [comment]
@travist @Blackbaud-ScottVossen hopefully within the next hour or two, I've identified the issue, and I'm currently stepping though the code to fix it.

**Comment by zackurben** [comment]
I actually just fixed it, so I need to do some smoke testing and check for regressions then we can start the process.

**Comment by travist** [comment]
We just released version ***v2.3.4*** of the renderer with this fix in place. Thanks again @Blackbaud-ScottVossen!

**Pull request merged**
